controllers:
    resource:
        path: ../src/Application/Controller/
        namespace: App\Application\Controller
    type: attribute
api:
    resource:
        path: ../src/Application/Controller
        namespace: App\Application\Controller
    type: attribute
    prefix: /api