App\Domain\Entity\Booking:
  attributes:
    bookingId:
      groups: [ 'STAY' ]
    hotel:
      groups: [ 'STAY' ]
    locator:
      groups: [ 'STAY' ]
    room:
      groups: [ 'STAY' ]
    checkIn:
      groups: [ 'STAY' ]
    checkOut:
      groups: [ 'STAY' ]
    numberOfNights:
      groups: [ 'STAY' ]
    totalPax:
      groups: [ 'STAY' ]
    guests:
      groups: [ 'STAY' ]